controllerwf: {

#Parameters for PID in simple_explorer

GP_left: 11.25, #15.0
GI_left: 2.0,
GD_left: 0.0,
Gcontr_left: 0.0,
setpoint_left: 0.0, #-0.01


GP_right: -0.0, #-15
GI_right: 0.0,
GD_right: 0.0,
Gcontr_right: 0.0,
setpoint_right: 0.0,

contr_time: 0.02,
contr_freq: 50.0
}
