controller3: {

  Gp_R: 10.0,
  Gp_L: 10.0,
  Gi_R: 0.9,
  Gi_L: 0.9,
  Gd_R: 0.1,
  Gd_L: 0.1,
  Gc_R: 0.0,
  Gc_L: 0.0,
  control_freq: 50,
  control_time: 0.02,
  satMin: 40.0,
  satMax: 150.0
}


controller_turn_old: { #_old
  Gp_R: 0.0450,
  Gp_L: 0.050,
  Gi_R: 0.005,
  Gi_L: 0.006,
  Gd_R: 0.015,
  Gd_L: 0.015,
  Gc_R: 0.00,
  Gc_L: 0.00,
  
  satMin: 0.1,
  satMax: 150.0
}

controller_turn_save50: { #_newsave50
  Gp_R: 0.15,
  Gp_L: 0.15,
  Gi_R: 0.02,
  Gi_L: 0.02,
  Gd_R: 0.0,
  Gd_L: 0.0,
  Gc_R: 0.00,
  Gc_L: 0.00,
  
  satMin: 0.1,
  satMax: 150.0
}


controller_turn_new_oldBATT: { #_old_lowBATT
  Gp_R: 0.19,
  Gp_L: 0.21,
  Gi_R: 0.019,
  Gi_L: 0.021,
  Gd_R: 0.028,
  Gd_L: 0.032,
  Gc_R: 0.0,
  Gc_L: 0.0,
  
  satMin: 0.1,
  satMax: 150.0
}



controller_turn_fast: { #_new_fast
  Gp_R: 0.20,
  Gp_L: 0.33,
  Gi_R: 0.2,
  Gi_L: 0.25,
  Gd_R: 0.1,
  Gd_L: 0.1,
  Gc_R: -0.15,
  Gc_L: -0.1,
  
  satMin: 0.1,
  satMax: 150.0
}

controller_turn: { #_new_lowBATT
  Gp_R: 0.29,
  Gp_L: 0.34,
  Gi_R: 0.023,
  Gi_L: 0.025,
  Gd_R: 0.03,
  Gd_L: 0.04,
  Gc_R: 0.0,
  Gc_L: 0.0,

  
  satMin: 0.1,
  satMax: 150.0
}
